/* Meal database — ingredients normalised for UK supermarkets (Tesco, Sainsbury's etc.)
   All meals follow Longo's Longevity Diet principles:
   - Mostly plant-based, pescatarian
   - Legumes as main protein source
   - Low-mercury fish only (salmon, sardines, cod, trout, sea bream, prawns, anchovies, clams)
   - Whole grains, generous olive oil, nuts
   - No red meat, minimal dairy, low sugar
*/

const MEALS = {
  breakfast: [
    {
      id: 'b1',
      name: 'Porridge with Berries & Walnuts',
      difficulty: 1,
      time: 10,
      description: 'Creamy jumbo oats cooked with oat milk, topped with fresh blueberries, walnuts, and a drizzle of honey.',
      method: 'Simmer 50g oats with 250ml oat milk for 5 min. Top with berries, walnuts, cinnamon, and a small drizzle of honey.',
      ingredients: [
        { name: 'Jumbo porridge oats', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Oat milk', qty: 250, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Blueberries', qty: 80, unit: 'g', cat: 'produce' },
        { name: 'Walnut halves', qty: 15, unit: 'g', cat: 'nuts_seeds' },
        { name: 'Ground cinnamon', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Runny honey', qty: 1, unit: 'tsp', cat: 'pantry' },
      ],
    },
    {
      id: 'b2',
      name: 'Overnight Oats with Almonds',
      difficulty: 1,
      time: 5,
      description: 'No-cook oats soaked overnight in almond milk with chia seeds and sliced almonds.',
      method: 'The night before: combine oats, almond milk, chia, a dash of vanilla. Fridge overnight. Top with berries and almonds.',
      ingredients: [
        { name: 'Jumbo porridge oats', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Unsweetened almond milk', qty: 200, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Chia seeds', qty: 1, unit: 'tbsp', cat: 'nuts_seeds' },
        { name: 'Flaked almonds', qty: 15, unit: 'g', cat: 'nuts_seeds' },
        { name: 'Raspberries', qty: 60, unit: 'g', cat: 'produce' },
      ],
    },
    {
      id: 'b3',
      name: 'Avocado & Tomato Sourdough',
      difficulty: 1,
      time: 8,
      description: 'Toasted wholemeal sourdough with smashed avocado, cherry tomatoes, lemon and olive oil.',
      method: 'Toast sourdough. Mash avocado with lemon juice and sea salt. Top with halved cherry tomatoes and a drizzle of olive oil.',
      ingredients: [
        { name: 'Wholemeal sourdough', qty: 2, unit: 'slices', cat: 'bakery' },
        { name: 'Ripe avocado', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Cherry tomatoes', qty: 100, unit: 'g', cat: 'produce' },
        { name: 'Lemon', qty: 0.25, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 1, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'b4',
      name: 'Chia Pudding with Mango',
      difficulty: 1,
      time: 5,
      description: 'Coconut-milk chia pudding prepared overnight, topped with fresh mango and toasted coconut.',
      method: 'Mix chia with coconut milk and maple syrup. Fridge overnight. Top with mango cubes and coconut flakes.',
      ingredients: [
        { name: 'Chia seeds', qty: 3, unit: 'tbsp', cat: 'nuts_seeds' },
        { name: 'Light coconut milk', qty: 200, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Maple syrup', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Fresh mango', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Coconut flakes', qty: 1, unit: 'tbsp', cat: 'nuts_seeds' },
      ],
    },
    {
      id: 'b5',
      name: 'Muesli Bowl with Fresh Fruit',
      difficulty: 1,
      time: 3,
      description: 'Unsweetened muesli with oat milk, sliced banana, and a scattering of mixed nuts.',
      method: 'Pour muesli into a bowl, add oat milk, top with sliced banana and nuts.',
      ingredients: [
        { name: 'Unsweetened muesli', qty: 60, unit: 'g', cat: 'pantry' },
        { name: 'Oat milk', qty: 200, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Banana', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Mixed unsalted nuts', qty: 20, unit: 'g', cat: 'nuts_seeds' },
      ],
    },
    {
      id: 'b6',
      name: 'Italian Tomato Bruschetta',
      difficulty: 1,
      time: 8,
      description: 'Longo-style breakfast: toasted sourdough rubbed with garlic, topped with tomatoes, basil and olive oil.',
      method: 'Toast bread. Rub with halved garlic clove. Top with chopped tomatoes, torn basil, olive oil, sea salt.',
      ingredients: [
        { name: 'Wholemeal sourdough', qty: 2, unit: 'slices', cat: 'bakery' },
        { name: 'Cherry tomatoes', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Garlic', qty: 1, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh basil', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 1, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'b7',
      name: 'Almond Butter Toast with Banana',
      difficulty: 1,
      time: 5,
      description: 'Wholemeal toast with almond butter, sliced banana, and a sprinkle of pumpkin seeds.',
      method: 'Toast bread. Spread with almond butter, top with banana slices and pumpkin seeds.',
      ingredients: [
        { name: 'Wholemeal bread', qty: 2, unit: 'slices', cat: 'bakery' },
        { name: 'Almond butter', qty: 2, unit: 'tbsp', cat: 'pantry' },
        { name: 'Banana', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Pumpkin seeds', qty: 1, unit: 'tbsp', cat: 'nuts_seeds' },
      ],
    },
    {
      id: 'b8',
      name: 'Berry Smoothie Bowl',
      difficulty: 1,
      time: 7,
      description: 'Blended frozen berries with banana and almond milk, topped with granola and seeds.',
      method: 'Blend frozen berries, banana, and almond milk until thick. Top with granola, chia, and fresh berries.',
      ingredients: [
        { name: 'Frozen mixed berries', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Banana', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Unsweetened almond milk', qty: 100, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Unsweetened granola', qty: 30, unit: 'g', cat: 'pantry' },
        { name: 'Chia seeds', qty: 1, unit: 'tsp', cat: 'nuts_seeds' },
      ],
    },
  ],

  lunch: [
    {
      id: 'l1',
      name: 'Minestrone with Borlotti Beans',
      difficulty: 2,
      time: 35,
      description: 'Classic Italian vegetable soup with borlotti beans, tomato, and small pasta.',
      method: 'Sweat onion, carrot, celery in olive oil. Add tomatoes, stock, courgette, beans, and small pasta. Simmer 20 min. Finish with basil and olive oil.',
      ingredients: [
        { name: 'Tinned borlotti beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Carrot', qty: 2, unit: 'whole', cat: 'produce' },
        { name: 'Celery', qty: 2, unit: 'sticks', cat: 'produce' },
        { name: 'Courgette', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Vegetable stock cube', qty: 1, unit: 'whole', cat: 'pantry' },
        { name: 'Wholemeal pasta (small shapes)', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
        { name: 'Fresh basil', qty: 5, unit: 'g', cat: 'produce' },
      ],
    },
    {
      id: 'l2',
      name: 'Chickpea & Spinach Stew',
      difficulty: 2,
      time: 25,
      description: 'Spanish-style chickpeas with wilted spinach, smoked paprika, and cumin.',
      method: 'Fry onion and garlic, add spices, chickpeas, tomatoes. Simmer 15 min. Stir in spinach until wilted.',
      ingredients: [
        { name: 'Tinned chickpeas', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Fresh spinach', qty: 200, unit: 'g', cat: 'produce' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Smoked paprika', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Ground cumin', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l3',
      name: 'Lentil & Roast Veg Salad',
      difficulty: 2,
      time: 40,
      description: 'Puy lentils with roasted peppers, red onion, rocket, and lemon-tahini dressing.',
      method: 'Roast peppers and onion with olive oil, 25 min at 200°C. Toss with cooked lentils, rocket, and dressing.',
      ingredients: [
        { name: 'Puy lentils', qty: 100, unit: 'g', cat: 'pantry' },
        { name: 'Red pepper', qty: 2, unit: 'whole', cat: 'produce' },
        { name: 'Red onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Rocket', qty: 50, unit: 'g', cat: 'produce' },
        { name: 'Tahini', qty: 2, unit: 'tbsp', cat: 'pantry' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l4',
      name: 'Pasta e Fagioli',
      difficulty: 2,
      time: 30,
      description: 'Wholemeal pasta with cannellini beans, kale, garlic and rosemary — rustic Italian comfort.',
      method: 'Fry garlic and rosemary in olive oil. Add beans and stock, simmer. Add pasta and kale, cook until tender.',
      ingredients: [
        { name: 'Tinned cannellini beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Wholemeal pasta', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Kale', qty: 100, unit: 'g', cat: 'produce' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh rosemary', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Vegetable stock cube', qty: 1, unit: 'whole', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l5',
      name: 'Farro & Tomato Salad',
      difficulty: 2,
      time: 25,
      description: 'Nutty farro with cherry tomatoes, olives, cucumber, parsley, and lemon dressing.',
      method: 'Cook farro 20 min. Toss with chopped vegetables, olives, parsley, olive oil and lemon.',
      ingredients: [
        { name: 'Pearled farro', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Cherry tomatoes', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Cucumber', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Kalamata olives', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Fresh parsley', qty: 10, unit: 'g', cat: 'produce' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l6',
      name: 'Hummus & Veg Wholemeal Wrap',
      difficulty: 1,
      time: 8,
      description: 'Wholemeal wrap with hummus, grated carrot, cucumber, rocket, and roasted red pepper.',
      method: 'Spread hummus on wrap. Layer with vegetables and rocket. Roll tightly, slice in half.',
      ingredients: [
        { name: 'Wholemeal wraps', qty: 1, unit: 'whole', cat: 'bakery' },
        { name: 'Hummus', qty: 3, unit: 'tbsp', cat: 'pantry' },
        { name: 'Carrot', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Cucumber', qty: 0.25, unit: 'whole', cat: 'produce' },
        { name: 'Rocket', qty: 30, unit: 'g', cat: 'produce' },
        { name: 'Roasted red pepper (jar)', qty: 50, unit: 'g', cat: 'pantry' },
      ],
    },
    {
      id: 'l7',
      name: 'Butter Bean & Rosemary Soup',
      difficulty: 2,
      time: 25,
      description: 'Creamy blended butter bean soup with rosemary, garlic and a swirl of olive oil.',
      method: 'Sauté garlic and rosemary. Add beans and stock, simmer 15 min. Blend smooth. Serve with olive oil.',
      ingredients: [
        { name: 'Tinned butter beans', qty: 2, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh rosemary', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Vegetable stock cube', qty: 1, unit: 'whole', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
      ],
    },
    {
      id: 'l8',
      name: 'Quinoa Tabbouleh with Chickpeas',
      difficulty: 2,
      time: 25,
      description: 'Herby quinoa salad with chickpeas, tomato, cucumber, mint and parsley.',
      method: 'Cook quinoa 15 min and cool. Mix with chopped herbs, veg, chickpeas, lemon, and olive oil.',
      ingredients: [
        { name: 'Quinoa', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Tinned chickpeas', qty: 0.5, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Cherry tomatoes', qty: 100, unit: 'g', cat: 'produce' },
        { name: 'Cucumber', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Fresh parsley', qty: 20, unit: 'g', cat: 'produce' },
        { name: 'Fresh mint', qty: 10, unit: 'g', cat: 'produce' },
        { name: 'Lemon', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l9',
      name: 'Pearl Barley & Mushroom Risotto',
      difficulty: 3,
      time: 45,
      description: 'Creamy barley risotto with chestnut mushrooms, thyme, and toasted walnuts.',
      method: 'Sauté onion, garlic, mushrooms. Add barley, stir, then add stock ladle by ladle 30 min. Finish with thyme and walnuts.',
      ingredients: [
        { name: 'Pearl barley', qty: 100, unit: 'g', cat: 'pantry' },
        { name: 'Chestnut mushrooms', qty: 200, unit: 'g', cat: 'produce' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 2, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh thyme', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Walnut halves', qty: 20, unit: 'g', cat: 'nuts_seeds' },
        { name: 'Vegetable stock cube', qty: 1, unit: 'whole', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'l10',
      name: 'White Bean & Kale Salad',
      difficulty: 1,
      time: 15,
      description: 'Massaged kale with cannellini beans, red onion, sundried tomatoes, and lemon.',
      method: 'Massage kale with olive oil and lemon 2 min. Add beans, sliced onion, sundried tomatoes, and toss.',
      ingredients: [
        { name: 'Tinned cannellini beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Kale', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Red onion', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Sundried tomatoes (jar)', qty: 40, unit: 'g', cat: 'pantry' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
  ],

  dinner: [
    {
      id: 'd1',
      name: 'Baked Salmon with Roast Veg',
      difficulty: 2,
      time: 35,
      fish: true,
      description: 'Wild salmon fillet with a tray of roasted courgette, red pepper, and red onion.',
      method: 'Roast chopped veg with olive oil 20 min at 200°C. Add salmon on top, roast 12 more min. Finish with lemon.',
      ingredients: [
        { name: 'Wild salmon fillet', qty: 1, unit: 'fillet (120g)', cat: 'fish' },
        { name: 'Courgette', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Red pepper', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Red onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
        { name: 'Fresh dill', qty: 5, unit: 'g', cat: 'produce' },
      ],
    },
    {
      id: 'd2',
      name: 'Sardines on Sourdough',
      difficulty: 1,
      time: 12,
      fish: true,
      description: 'Tinned sardines in olive oil on wholemeal sourdough with tomato, lemon, and parsley.',
      method: 'Toast sourdough. Mash sardines with lemon juice. Pile onto toast with sliced tomato and parsley.',
      ingredients: [
        { name: 'Tinned sardines in olive oil', qty: 1, unit: 'tin (120g)', cat: 'pantry' },
        { name: 'Wholemeal sourdough', qty: 2, unit: 'slices', cat: 'bakery' },
        { name: 'Tomato', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Fresh parsley', qty: 10, unit: 'g', cat: 'produce' },
      ],
    },
    {
      id: 'd3',
      name: 'Lentil & Vegetable Curry',
      difficulty: 2,
      time: 35,
      description: 'Red lentil dhal with spinach, tomato, ginger and coconut milk — served with brown rice.',
      method: 'Fry onion, ginger, garlic, spices. Add lentils, tomatoes, coconut milk, simmer 20 min. Stir in spinach. Serve with rice.',
      ingredients: [
        { name: 'Red split lentils', qty: 150, unit: 'g', cat: 'pantry' },
        { name: 'Brown basmati rice', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Light coconut milk', qty: 200, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Fresh spinach', qty: 100, unit: 'g', cat: 'produce' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh ginger', qty: 20, unit: 'g', cat: 'produce' },
        { name: 'Ground cumin', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Ground turmeric', qty: 1, unit: 'tsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd4',
      name: 'Aubergine & Chickpea Tagine',
      difficulty: 2,
      time: 40,
      description: 'Moroccan-spiced aubergine, chickpea and apricot stew served with couscous.',
      method: 'Brown aubergine. Add onion, garlic, spices, chickpeas, tomatoes, apricots. Simmer 25 min. Serve with couscous.',
      ingredients: [
        { name: 'Aubergine', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Tinned chickpeas', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Dried apricots', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Wholewheat couscous', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Ras el hanout', qty: 2, unit: 'tsp', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd5',
      name: 'Cod with Cannellini Beans',
      difficulty: 2,
      time: 30,
      fish: true,
      description: 'Pan-seared cod on a bed of cannellini beans with spinach, garlic and lemon.',
      method: 'Simmer beans with garlic and spinach. Pan-sear cod 3 min each side. Serve on beans with lemon and olive oil.',
      ingredients: [
        { name: 'Cod fillet', qty: 1, unit: 'fillet (120g)', cat: 'fish' },
        { name: 'Tinned cannellini beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Fresh spinach', qty: 100, unit: 'g', cat: 'produce' },
        { name: 'Garlic', qty: 2, unit: 'cloves', cat: 'produce' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd6',
      name: 'Pasta with Sardines & Fennel',
      difficulty: 2,
      time: 25,
      fish: true,
      description: 'Sicilian classic: wholemeal pasta with sardines, fennel, pine nuts, and sultanas.',
      method: 'Sauté fennel and onion. Add sardines, sultanas, pine nuts. Toss with cooked pasta and a splash of pasta water.',
      ingredients: [
        { name: 'Wholemeal pasta', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Tinned sardines in olive oil', qty: 1, unit: 'tin (120g)', cat: 'pantry' },
        { name: 'Fennel bulb', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Pine nuts', qty: 20, unit: 'g', cat: 'nuts_seeds' },
        { name: 'Sultanas', qty: 20, unit: 'g', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd7',
      name: 'Butterbean & Veg Traybake',
      difficulty: 1,
      time: 40,
      description: 'Everything on one tray: butterbeans, cherry tomatoes, courgette, red onion, rosemary and garlic.',
      method: 'Toss all veg and drained beans with olive oil, rosemary, garlic. Roast 35 min at 200°C.',
      ingredients: [
        { name: 'Tinned butter beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Cherry tomatoes', qty: 200, unit: 'g', cat: 'produce' },
        { name: 'Courgette', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Red onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 4, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh rosemary', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 3, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd8',
      name: 'Baked Sea Bream with Potatoes',
      difficulty: 2,
      time: 40,
      fish: true,
      description: 'Whole sea bream baked on sliced new potatoes with lemon, garlic, and fresh herbs.',
      method: 'Layer potatoes with olive oil, garlic, herbs. Roast 20 min. Add fish on top, roast 15 more min.',
      ingredients: [
        { name: 'Whole sea bream', qty: 1, unit: 'whole', cat: 'fish' },
        { name: 'New potatoes', qty: 300, unit: 'g', cat: 'produce' },
        { name: 'Lemon', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh thyme', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 3, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd9',
      name: 'Prawn & Veg Brown Rice Stir-Fry',
      difficulty: 2,
      time: 25,
      fish: true,
      description: 'King prawns stir-fried with broccoli, pepper, and spring onion, tossed with brown rice.',
      method: 'Cook rice. Stir-fry ginger, garlic, veg 5 min. Add prawns 3 min. Toss with rice, soy sauce, sesame oil.',
      ingredients: [
        { name: 'Raw king prawns', qty: 150, unit: 'g', cat: 'fish' },
        { name: 'Brown basmati rice', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Tenderstem broccoli', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Red pepper', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Spring onion', qty: 3, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 2, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh ginger', qty: 15, unit: 'g', cat: 'produce' },
        { name: 'Reduced-salt soy sauce', qty: 1, unit: 'tbsp', cat: 'pantry' },
        { name: 'Sesame oil', qty: 1, unit: 'tsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd10',
      name: 'Stuffed Peppers with Quinoa & Beans',
      difficulty: 2,
      time: 45,
      description: 'Red peppers stuffed with quinoa, black beans, corn, tomato, and spices, baked until tender.',
      method: 'Cook quinoa. Mix with beans, corn, tomato, spices. Fill peppers. Bake 30 min at 200°C.',
      ingredients: [
        { name: 'Red pepper', qty: 2, unit: 'whole', cat: 'produce' },
        { name: 'Quinoa', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Tinned black beans', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Tinned sweetcorn', qty: 1, unit: 'tin (195g)', cat: 'pantry' },
        { name: 'Tomato', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Ground cumin', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Smoked paprika', qty: 1, unit: 'tsp', cat: 'pantry' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd11',
      name: 'Mediterranean Bean Stew',
      difficulty: 1,
      time: 30,
      description: 'Hearty mixed bean stew with fennel, tomato, rosemary, and olives — crusty bread to mop up.',
      method: 'Sauté fennel and garlic. Add tomatoes, beans, olives, rosemary. Simmer 20 min. Serve with bread.',
      ingredients: [
        { name: 'Tinned mixed beans', qty: 2, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Fennel bulb', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Kalamata olives', qty: 50, unit: 'g', cat: 'pantry' },
        { name: 'Garlic', qty: 3, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh rosemary', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Wholemeal sourdough', qty: 2, unit: 'slices', cat: 'bakery' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd12',
      name: 'Trout with Lemon & Herbs',
      difficulty: 2,
      time: 25,
      fish: true,
      description: 'Pan-fried rainbow trout fillets with lemon, capers, parsley, and steamed greens.',
      method: 'Pan-fry trout skin-side down 4 min, flip 2 min. Make sauce with pan juices, lemon, capers. Serve with greens.',
      ingredients: [
        { name: 'Rainbow trout fillet', qty: 1, unit: 'fillet (120g)', cat: 'fish' },
        { name: 'Tenderstem broccoli', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Lemon', qty: 0.5, unit: 'whole', cat: 'produce' },
        { name: 'Capers', qty: 1, unit: 'tbsp', cat: 'pantry' },
        { name: 'Fresh parsley', qty: 10, unit: 'g', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd13',
      name: 'Mushroom & Chestnut Ragu',
      difficulty: 2,
      time: 35,
      description: 'Rich mushroom and chestnut ragu with red wine and thyme, served over wholemeal pappardelle.',
      method: 'Sauté onion, garlic, mushrooms. Add chestnuts, wine, tomatoes, thyme. Simmer 20 min. Serve over pasta.',
      ingredients: [
        { name: 'Mixed mushrooms', qty: 250, unit: 'g', cat: 'produce' },
        { name: 'Cooked chestnuts', qty: 100, unit: 'g', cat: 'pantry' },
        { name: 'Wholemeal pasta', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 2, unit: 'cloves', cat: 'produce' },
        { name: 'Red wine', qty: 100, unit: 'ml', cat: 'pantry' },
        { name: 'Fresh thyme', qty: 5, unit: 'g', cat: 'produce' },
        { name: 'Extra virgin olive oil', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 'd14',
      name: 'Chickpea & Spinach Curry',
      difficulty: 1,
      time: 25,
      description: 'Quick chickpea curry with spinach, coconut milk, and garam masala.',
      method: 'Sauté onion, garlic, ginger, spices. Add chickpeas, coconut milk, tomatoes. Simmer 15 min. Stir in spinach.',
      ingredients: [
        { name: 'Tinned chickpeas', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Fresh spinach', qty: 150, unit: 'g', cat: 'produce' },
        { name: 'Light coconut milk', qty: 200, unit: 'ml', cat: 'dairy_alt' },
        { name: 'Tinned chopped tomatoes', qty: 1, unit: 'tin (400g)', cat: 'pantry' },
        { name: 'Brown basmati rice', qty: 80, unit: 'g', cat: 'pantry' },
        { name: 'Onion', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Garlic', qty: 2, unit: 'cloves', cat: 'produce' },
        { name: 'Fresh ginger', qty: 15, unit: 'g', cat: 'produce' },
        { name: 'Garam masala', qty: 2, unit: 'tsp', cat: 'pantry' },
      ],
    },
  ],

  snack: [
    {
      id: 's1',
      name: 'Mixed Nuts',
      difficulty: 1,
      time: 1,
      description: 'A small handful (30g) of unsalted mixed nuts — Longo recommends ~1oz/30g daily.',
      method: 'Portion 30g into a small bowl or container.',
      ingredients: [
        { name: 'Mixed unsalted nuts', qty: 30, unit: 'g', cat: 'nuts_seeds' },
      ],
    },
    {
      id: 's2',
      name: 'Apple with Almond Butter',
      difficulty: 1,
      time: 2,
      description: 'Sliced apple with a tablespoon of almond butter.',
      method: 'Slice apple, serve with almond butter for dipping.',
      ingredients: [
        { name: 'Apple', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Almond butter', qty: 1, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 's3',
      name: 'Carrot & Hummus',
      difficulty: 1,
      time: 3,
      description: 'Carrot sticks with hummus — simple and satisfying.',
      method: 'Cut carrots into sticks, serve with 2 tbsp hummus.',
      ingredients: [
        { name: 'Carrot', qty: 1, unit: 'whole', cat: 'produce' },
        { name: 'Hummus', qty: 2, unit: 'tbsp', cat: 'pantry' },
      ],
    },
    {
      id: 's4',
      name: 'Walnuts & Dates',
      difficulty: 1,
      time: 1,
      description: 'A few medjool dates stuffed with walnut halves.',
      method: 'Slit dates, remove stones, stuff each with a walnut half.',
      ingredients: [
        { name: 'Medjool dates', qty: 3, unit: 'whole', cat: 'produce' },
        { name: 'Walnut halves', qty: 15, unit: 'g', cat: 'nuts_seeds' },
      ],
    },
    {
      id: 's5',
      name: 'Oatcakes with Avocado',
      difficulty: 1,
      time: 3,
      description: 'Rough oatcakes topped with mashed avocado and cracked pepper.',
      method: 'Mash avocado. Top oatcakes with avocado and black pepper.',
      ingredients: [
        { name: 'Rough oatcakes', qty: 3, unit: 'whole', cat: 'bakery' },
        { name: 'Ripe avocado', qty: 0.5, unit: 'whole', cat: 'produce' },
      ],
    },
    {
      id: 's6',
      name: 'Coconut Yogurt with Berries',
      difficulty: 1,
      time: 2,
      description: 'Unsweetened coconut yogurt with fresh raspberries and a sprinkle of flaxseed.',
      method: 'Spoon yogurt into bowl, top with raspberries and flaxseed.',
      ingredients: [
        { name: 'Unsweetened coconut yogurt', qty: 100, unit: 'g', cat: 'dairy_alt' },
        { name: 'Raspberries', qty: 60, unit: 'g', cat: 'produce' },
        { name: 'Ground flaxseed', qty: 1, unit: 'tsp', cat: 'nuts_seeds' },
      ],
    },
  ],
};

const CATEGORY_LABELS = {
  produce: 'Fresh Produce',
  pantry: 'Pantry & Dry Goods',
  fish: 'Fish & Seafood',
  dairy_alt: 'Plant-Based Dairy',
  bakery: 'Bakery',
  nuts_seeds: 'Nuts & Seeds',
};

const CATEGORY_ORDER = ['produce', 'fish', 'bakery', 'dairy_alt', 'nuts_seeds', 'pantry'];
